# .pre-commit-config.yaml

- repo: https://github.com/prettier/miscellaneous
  rev: v2.0.0
  hooks:
    - id: prettier
      files: \.(js|json|css|scss|html|yaml|md|toml|py|yml)$
      types: [file]

- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
    - id: black
      language_version: python3

- repo: https://github.com/PyCQA/flake8
  rev: v4.0.0
  hooks:
    - id: flake8
      args: [--max-line-length=100]
      language_version: python3

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
    - id: mypy
      language_version: python3

- repo: https://github.com/django-dbtemplates/pre-commit-hooks
  rev: v1.0.1
  hooks:
    - id: fix-python-encoding
      name: Ensure Python files have correct encoding
      entry: python3 -m fix_encoding
      language: python

